import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve('public');
const taxonomy=fs.readFileSync(path.join(root,'product-taxonomy.js'),'utf8');
const page=fs.readFileSync(path.join(root,'baskets.html'),'utf8');
const js=fs.readFileSync(path.join(root,'basket-discovery-v1.js'),'utf8');
const css=fs.readFileSync(path.join(root,'basket-discovery-v1.css'),'utf8');
test('34 canonical baskets',()=>{assert.equal((taxonomy.match(/^\s*\['[^']+',/gm)||[]).length,34);assert.match(taxonomy,/exactly 34 approved product baskets/)});
test('canonical API boundary only',()=>{assert.match(js,/https:\/\/api\.afaghx\.com\/v1\/search/);assert.match(js,/PRODUCT_TAXONOMY/);assert.doesNotMatch(js,/localhost|127\.0\.0\.1|mock|fixture/i)});
test('no invented hierarchy or commercial truth',()=>{assert.match(js,/No family, sub-basket or commercial record is invented/);assert.match(js,/داده ساختگی نمایش داده نمی‌شود/);assert.doesNotMatch(js,/price|rating|verified|score/i)});
test('bilingual direction and switch',()=>{assert.match(page,/lang="fa" dir="rtl"/);assert.match(js,/document\.documentElement\.lang/);assert.match(js,/document\.documentElement\.dir/);assert.match(js,/\?lang=/);assert.match(js,/fa\?'en':'fa'/)});
test('responsive accessibility baseline',()=>{assert.match(css,/max-width:900px/);assert.match(css,/max-width:620px/);assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/focus-visible/);assert.match(js,/role="status"/)});
console.log('Basket discovery contract: 34 baskets + canonical API + no fabrication + bilingual/accessibility verified');