import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve('public');
const taxonomy=fs.readFileSync(path.join(root,'product-taxonomy.js'),'utf8');
const page=fs.readFileSync(path.join(root,'baskets.html'),'utf8');
const js=fs.readFileSync(path.join(root,'basket-discovery-v1.js'),'utf8');
const css=fs.readFileSync(path.join(root,'basket-discovery-v1.css'),'utf8');
test('canonical taxonomy is exactly 34 baskets',()=>{const rows=taxonomy.match(/^\s*\['[^']+',/gm)||[];assert.equal(rows.length,34);assert.match(taxonomy,/exactly 34 approved product baskets/)});
test('discovery uses the canonical taxonomy and API boundary',()=>{assert.match(js,/import \{ PRODUCT_TAXONOMY \} from '\.\/product-taxonomy\.js'/);assert.match(js,/https:\/\/api\.afaghx\.com/);assert.match(js,/\/v1\/search/);assert.doesNotMatch(js,/localhost|127\.0\.0\.1|mock|fixture/i)});
test('language separation is explicit',()=>{assert.match(page,/lang="fa" dir="rtl"/);assert.match(js,/document\.documentElement\.lang=state\.lang/);assert.match(js,/document\.documentElement\.dir=fa\?'rtl':'ltr'/);assert.match(js,/lang=\$\{fa\?'en':'fa'\}/)});
test('language separation is explicit',()=>{assert.match(page,/lang="fa" dir="rtl"/);assert.match(js,/document\.documentElement\.lang=state\.lang/);assert.match(js,/document\.documentElement\.dir=fa\?'rtl':'ltr'/);assert.match(js,/lang=\\\$\{fa\?'en':'fa'\}/)});
test('responsive and accessibility contracts exist',()=>{assert.match(css,/max-width:900px/);assert.match(css,/max-width:620px/);assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/focus-visible/);assert.match(js,/role="status"/)});
console.log('Basket discovery contract: 34 taxonomy entries + API boundary + bilingual/accessibility contracts verified');