import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve('public');
const taxonomy=fs.readFileSync(path.join(root,'product-taxonomy.js'),'utf8');
const page=fs.readFileSync(path.join(root,'baskets.html'),'utf8');
const js=fs.readFileSync(path.join(root,'basket-discovery-v1.js'),'utf8');
const css=fs.readFileSync(path.join(root,'basket-discovery-v1.css'),'utf8');
test('live result with id links to Product detail without inventing truth',()=>{assert.match(js,/\.\/products\/index\.html\?id=/);assert.match(js,/encodeURIComponent\(String\(id\)\)/);assert.match(js,/x\?\.id/);});
